services:
  - type: web
    name: petcare-backend
    runtime: java
    repo: https://github.com/danielwav/PetCare-Backend
    branch: dev
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/petcare-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: JPA_DDL_AUTO
        value: update
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: petcare-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: petcare-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: petcare-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: petcare-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: petcare-db
    databaseName: petcare
    region: ohio
    plan: free
