branch-defaults:
  dev:
    environment: petcare-backend-prod
  main:
    environment: null
    group_suffix: null
  prueba:
    environment: petcare-backend-prod
global:
  application_name: petcare-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 21
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
