spring.application.name=PetCare-Backend

server.port=${SERVER_PORT:8090}
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# --- Resend (Email) ---
RESEND_API_KEY=${RESEND_API_KEY:re_3Qy4d2Fj_DMtn4E4nrDmDBCyiMVpQrYBL}
RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:onboarding@resend.dev}
RESEND_API_URL=${RESEND_API_URL:https://api.resend.com/emails}

app.base-url=${APP_BASE_URL:http://localhost:4200}
app.mail.enabled=${MAIL_ENABLED:true}

security.jwt.secret=${JWT_SECRET:UGV0Q2FyZS1EZXZlbG9wbWVudC1KMFQtU2VjcmV0LTIwMjYtU3VwZXItU2VndXJhLUNhbWJpYXJFbkVudg==}
security.jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:3600000}
security.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}