-- Only for a disposable local PostgreSQL database, never a deployed database.
\set ON_ERROR_STOP on
DO $$ BEGIN
    IF current_database() <> 'p2_migration_test' THEN
        RAISE EXCEPTION 'Tests require disposable database p2_migration_test';
    END IF;
END $$;
CREATE SCHEMA p2_test;
SET search_path = p2_test, pg_catalog;
CREATE TABLE clinicas (id bigint PRIMARY KEY, slug varchar(100) UNIQUE NOT NULL);
INSERT INTO clinicas VALUES (1, 'demo'), (2, 'other'), (3, 'empty');
CREATE TABLE usuarios (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas);
CREATE TABLE duenios (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas,
    usuario_id bigint UNIQUE, email varchar(120) UNIQUE NOT NULL, numero_documento varchar(20) NOT NULL);
CREATE UNIQUE INDEX legacy_owner_document ON duenios (numero_documento);
CREATE TABLE servicios (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas,
    nombre varchar(100) NOT NULL);
CREATE UNIQUE INDEX legacy_service_name ON servicios (nombre);
CREATE UNIQUE INDEX keep_service_partial ON servicios (nombre) WHERE id < 0;
CREATE INDEX keep_service_expression ON servicios (upper(nombre));
CREATE TABLE mascotas (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas,
    duenio_id bigint REFERENCES duenios);
CREATE TABLE citas (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas);
CREATE TABLE veterinarios (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas);
CREATE TABLE asistentes (id bigint PRIMARY KEY, clinica_id bigint REFERENCES clinicas);
-- Pre-P2 catalog intentionally lacks clinica_id.
CREATE TABLE vacunas (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(120) UNIQUE NOT NULL, descripcion varchar(500) NOT NULL,
    intervalo_proxima_dosis_dias integer, active boolean NOT NULL,
    created_at timestamp NOT NULL, updated_at timestamp NOT NULL);
CREATE TABLE vacunas_mascota (id bigint PRIMARY KEY, mascota_id bigint REFERENCES mascotas,
    vacuna_id bigint REFERENCES vacunas, veterinario_id bigint, cita_id bigint,
    fecha_aplicacion date, lote varchar(80), fecha_proxima_dosis date,
    observaciones varchar(500), created_at timestamp NOT NULL);
INSERT INTO duenios VALUES (1, 1, NULL, 'owner@example.test', '123');
INSERT INTO servicios VALUES (1, 1, 'Consulta');
INSERT INTO mascotas VALUES (1, 1, 1), (2, 2, NULL);
INSERT INTO vacunas (nombre, descripcion, intervalo_proxima_dosis_dias, active, created_at, updated_at)
VALUES ('Rabia', 'Historical description', 365, false, '2020-01-01', '2021-01-01'),
       ('Unused', 'No applications', NULL, true, '2020-01-01', '2021-01-01');
INSERT INTO vacunas_mascota VALUES
    (1, 1, 1, 5, 8, '2021-01-01', 'old-demo', '2022-01-01', 'demo history', '2021-01-01'),
    (2, 2, 1, 6, 9, '2021-02-01', 'old-other', '2022-02-01', 'other history', '2021-02-01'),
    (3, 2, 1, 6, NULL, '2022-02-01', 'repeat', '2023-02-01', 'repeat history', '2022-02-01');
CREATE TABLE history_before AS SELECT id, to_jsonb(vm) - 'vacuna_id' AS data FROM vacunas_mascota vm;
\ir p2-preflight.sql
\ir p2-tenant-migration.sql
\ir p2-tenant-migration.sql
DO $$ BEGIN
    IF (SELECT count(*) FROM vacunas) <> 3 THEN RAISE EXCEPTION 'Clone count/idempotency'; END IF;
    IF EXISTS (SELECT 1 FROM vacunas WHERE clinica_id IS NULL OR clinica_id = 3) THEN
        RAISE EXCEPTION 'Null catalog or empty clinic populated';
    END IF;
    IF (SELECT clinica_id FROM vacunas WHERE id = 1) <> 1 THEN RAISE EXCEPTION 'Original moved'; END IF;
    IF EXISTS (SELECT 1 FROM vacunas_mascota vm JOIN mascotas m ON m.id = vm.mascota_id
        JOIN vacunas v ON v.id = vm.vacuna_id WHERE m.clinica_id <> v.clinica_id) THEN
        RAISE EXCEPTION 'Historical remapping';
    END IF;
    IF EXISTS (SELECT 1 FROM history_before b FULL JOIN vacunas_mascota vm ON vm.id = b.id
        WHERE b.data IS DISTINCT FROM (to_jsonb(vm) - 'vacuna_id')) THEN
        RAISE EXCEPTION 'History changed';
    END IF;
    IF (SELECT to_jsonb(v) - 'id' - 'clinica_id' FROM vacunas v WHERE clinica_id = 2)
        IS DISTINCT FROM (SELECT to_jsonb(v) - 'id' - 'clinica_id' FROM vacunas v WHERE id = 1) THEN
        RAISE EXCEPTION 'Clone fields changed';
    END IF;
    IF to_regclass('legacy_service_name') IS NOT NULL OR to_regclass('legacy_owner_document') IS NOT NULL
       OR to_regclass('keep_service_partial') IS NULL OR to_regclass('keep_service_expression') IS NULL
       OR NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'duenios'::regclass
                      AND conname = 'duenios_usuario_id_key') THEN
        RAISE EXCEPTION 'Unrelated uniqueness changed or legacy uniqueness retained';
    END IF;
    BEGIN
        INSERT INTO servicios VALUES (2, 1, 'consulta');
        RAISE EXCEPTION 'IgnoreCase service duplicate accepted';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;
    BEGIN
        INSERT INTO vacunas (clinica_id, nombre, descripcion, active, created_at, updated_at)
        VALUES (1, 'RABIA', 'duplicate', true, now(), now());
        RAISE EXCEPTION 'IgnoreCase vaccine duplicate accepted';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;
    BEGIN
        INSERT INTO duenios VALUES (2, 1, NULL, 'owner@example.test', 'different');
        RAISE EXCEPTION 'Duplicate tenant email accepted';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;
    BEGIN
        INSERT INTO duenios VALUES (2, 1, NULL, 'different@example.test', '123');
        RAISE EXCEPTION 'Duplicate tenant document accepted';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;
END $$;
INSERT INTO servicios VALUES (2, 2, 'Consulta');
INSERT INTO duenios VALUES (2, 2, NULL, 'owner@example.test', '123');
\ir p2-preflight.sql
